namespace JuiceShopDotNet.Safe.Cryptography.KeyStorage;

public interface IKeyStore
{
    /// <summary>
    /// Gets the full key from the key store.
    /// </summary>
    /// <returns>String representation of the key</returns>
    string GetKey(string keyName, int keyIndex);

    /// <summary>
    /// Saves a key name and value to the database (use if keys need to be in a different format than the ones automatically generated by GetFullKey)
    /// </summary>
    /// <returns>Index of new key</returns>
    int CreateKey(string keyName, int keyLength);

    /// <summary>
    /// Saves a key name and value to the database (use if keys need to be in a different format than the ones automatically generated by GetFullKey)
    /// </summary>
    /// <returns>Index of new key</returns>
    int CreateKey(string keyName, string keyValue);
}
